apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
    link.argocd.argoproj.io/external-link: http://codefresh.io

spec:
  replicas: 6
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
        - name: canary-demo
          image: idanarbel/rollouts-demo:yellow
          #image: idanarbel/rollouts-demo:purple
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
  strategy:
    canary:
      canaryService: canary-demo-preview
      steps:
        - setWeight: 10
        - pause: {}
        - setWeight: 50
        - pause: {duration: 25}
        - setWeight: 80
        - pause: {duration: 25}
